// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD42WsKOyvS5PK1L-aTqp1E6o7S_2F1at8',  
    appId: '1:131580585956:web:cc816569be5e40b8d409f1',
    messagingSenderId: '131580585956',
    projectId: 'finance-app-364116',
    authDomain: 'finance-app-364116.firebaseapp.com',
    storageBucket: 'finance-app-364116.appspot.com',
    measurementId: 'G-NQCKXDY7CH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBHu-_gyG7JK4SYy14tXLctL6BQmqcZilg',
    appId: '1:131580585956:android:d1ff1def5bbfbdf1d409f1',
    messagingSenderId: '131580585956',
    projectId: 'finance-app-364116',
    storageBucket: 'finance-app-364116.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDxWuTHSn1Edp3KLzwL2lKRZnRKy3yPRxg',
    appId: '1:131580585956:ios:14d976f2aa8b0d02d409f1',
    messagingSenderId: '131580585956',
    projectId: 'finance-app-364116',
    storageBucket: 'finance-app-364116.appspot.com',
    androidClientId: '131580585956-j2i7kvqdntmmsrvfp2phtqpsuraf3kh1.apps.googleusercontent.com',
    iosClientId: '131580585956-3t1flgm9g2a28s5gn8cl04po5auhq0tk.apps.googleusercontent.com',
    iosBundleId: 'com.example.financeGestionApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDxWuTHSn1Edp3KLzwL2lKRZnRKy3yPRxg',
    appId: '1:131580585956:ios:14d976f2aa8b0d02d409f1',
    messagingSenderId: '131580585956',
    projectId: 'finance-app-364116',
    storageBucket: 'finance-app-364116.appspot.com',
    androidClientId: '131580585956-j2i7kvqdntmmsrvfp2phtqpsuraf3kh1.apps.googleusercontent.com',
    iosClientId: '131580585956-3t1flgm9g2a28s5gn8cl04po5auhq0tk.apps.googleusercontent.com',
    iosBundleId: 'com.example.financeGestionApp',
  );
}
